### ISSUE TITLE
How to search for a string of text in header that isn't on row 1?

### ISSUE THREAD

**Issue by mhanson7** [MarkPflug/Sylvan.Data.Excel#12]
I've got a report that is a daily data extract.  The location of the column header that I'm looking for is always changing, based on the export table that was defined.  Also, it's following after the metadata, which means that it's never on row 1.  How can I quickly search data, and extract an entire column, based on the cell that my query term is found in?

**Comment by MarkPflug** [comment]
My library doesn't currently support skipping header rows easily, I'll consider possibly adding that in the future.
For now, you can do something like the following code to do what you need:

```
using Sylvan.Data.Excel;

// the name of the column header you're looking for
const string ColumnName = "mycol";

// create an excel data reader with headers disabled.
var opts = new ExcelDataReaderOptions { Schema = ExcelSchema.NoHeaders };
var r = ExcelDataReader.Create("data.xlsx", opts);

// will hold the located column index
int colIdx = -1;

// the  maximum number of rows to inspect looking for the header.
const int MaxHeaderRows = 5;

var row = 0;
// read rows and look for a column with the header text. 
while (r.Read())
{
    for (int i = 0; i < r.FieldCount; i++)
    {
        var col = r.GetString(i);
        if (StringComparer.OrdinalIgnoreCase.Equals(ColumnName, col))
        {
            Console.WriteLine($"Found header at {row}, {i}.");
            colIdx = i;
            break;
        }
    }
    // if we found the column, or we've exceed the max number of rows to inspect,
    // break out of the loop.
    if (colIdx > 0 || row++ > MaxHeaderRows)
    {
        break;
    }
}

// at point if we found the header, colIdx should hold it's column index
if (colIdx < 0)
{
    Console.WriteLine($"Could not find column with header {ColumnName}.");
    // maybe throw an exception in this case, becaues the excel format is not what you're expecting
}
else
{
    // iterate over the rest of the file and read out the column value.
    while (r.Read())
    {
        Console.WriteLine(r.GetString(colIdx));
    }
}



```

**Comment by mhanson7** [comment]
Is there a way to find the total number of rows and columns in the ExcelDataReader that is created?  Because when I try to use the FieldCount and RowCount, I don't get numbers that make sense.  Additionally, I'm not finding this code to return the proper column number.  (taking aside that Excel cells are 1 indexed, I don't get the correct number, when I try to comp the code for this)

**Comment by MarkPflug** [comment]
This would be a lot easier if you gave me a concrete example. Do you have, or can you create, an example file and code?

**Comment by mhanson7** [comment]
I created a test block with your code, verbatim. (save the Column name and file path)

**Comment by MarkPflug** [comment]
Without a sample file I'm going to be able to help you. Sorry.
