### ISSUE TITLE
Issue with OpenPackaging ".rel" paths

### ISSUE THREAD

**Issue by MarkPflug** [MarkPflug/Sylvan.Data.Excel#125]
The file provided by @Mek7 in https://github.com/MarkPflug/Sylvan.Data.Excel/issues/99#issuecomment-1611136046, contains OpenPackaging .rel paths that are "rooted" (start with a backslash), where typically these are relative. This is causing the code to not locate the appropriate zip entry, which is reported as an InvalidDataException.

**Comment by Mek7** [comment]
Thank you, yes, a fix would be nice, however, at this time I decided to go a different route to read the .xlsx file, not using the Sylvan nuget. But I'm sure it will also help others.
