### ISSUE TITLE
Xlsb - to many columns in filter

### ISSUE THREAD

**Issue by KrzysztofDusko** [MarkPflug/Sylvan.Data.Excel#140]
Hi,
xlsb files have to many column in filter (probably related to count from 1 instead of 0) :)
![image](https://github.com/MarkPflug/Sylvan.Data.Excel/assets/69449360/42d9990f-a6f6-4767-a8ed-b2d5ec45383c)

problaby this line causing this

https://github.com/MarkPflug/Sylvan.Data.Excel/blob/3db441d56e22ef96fd677d34475a275b4442b745/source/Sylvan.Data.Excel/Xlsb/XlsbDataWriter.cs#L547

**Comment by MarkPflug** [comment]
Thanks for the bug report and identifying the fix. Will be included in the next release, no ETA right now.
