### ISSUE TITLE
Unable to read the line OutputTax:Lineitems from Row 2 and column 1

### ISSUE THREAD

**Issue by SantoshRautTR** [MarkPflug/Sylvan.Data.Excel#143]
@MarkPflug 

We are unable to read the line OutputTax: LineItems string from Row#2 and column #1 from the attached file using the console code below . Can you please go thru it once.
[TEST_Summary_small.xlsx](https://github.com/MarkPflug/Sylvan.Data.Excel/files/13376125/TEST_Summary_small.xlsx)

Below is the console Application code used for reading the file contents.
https://gist.github.com/SantoshRautTR/bb37005653dc95dc464a50a89455f51b

**Comment by MarkPflug** [comment]
Thanks for the bug report. This is fixed in 0.4.18, which I just published to nuget. It might take a while to show up in the nuget index.
