### ISSUE TITLE
Access a cell formular string in Sylvan Data Excel

### ISSUE THREAD

**Issue by renderhjs** [MarkPflug/Sylvan.Data.Excel#145]
Hi Mark,

I am looking for a way to read the cell formula as plain string. It doesn't seem to be supported out of the box but I am wondering if you know a way to access to formula as string representation?
![image](https://github.com/MarkPflug/Sylvan.Data.Excel/assets/57063362/6aa9c329-073a-4409-8d38-5617ccb0c812)

Love the loading times from your library,

renderhjs

**Comment by MarkPflug** [comment]
No, unfortunately this is not supported. I try to maintain parity between the supported formats, and while it is easy enough to get the formula text for an .xlsx file, it is quite involved to get it for .xls and .xlsb files. If this is a feature you need, I'd suggest you use a more feature-rich library.
