### ISSUE TITLE
Xlsb in MS Excel 2016

### ISSUE THREAD

**Issue by KrzysztofDusko** [MarkPflug/Sylvan.Data.Excel#148]
Hello,
XLSB file created with dafault settiings cannot be sorted in Excel 2016.. (Excel crashes).

```c#
            using var edw = ExcelDataWriter.Create("fileSylvan.xlsb", new ExcelDataWriterOptions() {  CompressionLevel = cLvl});
            DbDataReader dr;
            dr = Dt.CreateDataReader(); // dt = some datatable but this is irrelevant
            edw.Write(dr, "sheetName");
```
![image](https://github.com/MarkPflug/Sylvan.Data.Excel/assets/69449360/3d8cf997-a267-4cb6-8cdc-36453f1e1954)

In excel 2019 everything works fine.. 
I have te same problem with my library :( (https://github.com/KrzysztofDusko/SpreadSheetTasks)  I will investigate this yourself in some time.

**Comment by KrzysztofDusko** [comment]
for sure issue is related with autofilter

**Comment by MarkPflug** [comment]
I think I've decided I'm going to ignore this issue. To me, this is a bug in Excel 2016, which has been fixed in later versions. Excel 2016 is old enough now that people should move on.
