### ISSUE TITLE
Header row error in XLS file

### ISSUE THREAD

**Issue by erikharaldsson** [MarkPflug/Sylvan.Data.Excel#149]
When I open a XLSX (or XLSB) file I can walk through all rows without any problems, but when I open a XLS file, then it will show the second row two times instead of the first and second row. It will say row number 1 then get the data for the second row. If I then use Read() to move to the second row then it shows it being at row 2 and reads the  same row a second time before moving on to the third row. Running GetColumnSchema() will show the columns on the first row in each case. I tried to call Initialize() after opening the file, but it didn't cause anything to change. 
The code I used:
``` C#
static void SylvanTest(string file)
        {
            try
            {
                using (var package = Sylvan.Data.Excel.ExcelDataReader.Create(file))
                {
                    var rowCount = package.RowCount;
                    Console.WriteLine(package.WorksheetName);
                    Console.WriteLine($"Total row count: {rowCount}");
                    Console.WriteLine(package.RowNumber);
                    foreach (var item in package.GetColumnSchema())
                        Console.WriteLine(item.ColumnName);
                    package.Initialize();
                    do
                     {
                         Console.WriteLine(package.RowNumber);
                         for (int c = 0; c < package.RowFieldCount; c++)
                         {
                             try
                             {
                                 Console.Write($"{package.GetExcelValue(c)} " +
                                     $"<{package.GetExcelValue(c).GetType()}>\t");
                             }
                             catch (Exception ex)
                             {
                                 Console.WriteLine(ex);
                             }
                         }
                         Console.WriteLine();
                     } while (package.Read());
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
```
[Bok2.xls](https://github.com/MarkPflug/Sylvan.Data.Excel/files/13854495/Bok2.xls)

**Comment by erikharaldsson** [comment]
Hi Mark,

That will skip the first row and start reading from the second row, are you saying that I should only try to access the first row by calling GetColumnSchema()?

**Comment by MarkPflug** [comment]
By default, the first row is expected to be headers. You would access the column name by calling `GetName(int ordinal)`. If the first row contains data, you should set the Schema option, to indicate such:

```C#
var opts = new ExcelDataReaderOptions { Schema = ExcelSchema.NoHeaders };
using var edr = ExcelDataReader.Create(file, opts);
```
