### ISSUE TITLE
Exception thrown when reading a XLSX or XLSB workbook with a chart sheet

### ISSUE THREAD

**Issue by roncrush** [MarkPflug/Sylvan.Data.Excel#151]
Thanks for the great library!

When I was trying to create a reader for an Excel file (XLSX) with a chart sheet a `KeyNotFoundException` was getting thrown. This also seems to be happening for XLSB files as well. In this case I wasn't trying to parse the chart sheet itself, instead I wanted to parse another worksheet that happened to be in the same workbook as the chart sheet.

Here's an example file: [ChartSheet.xlsx](https://github.com/MarkPflug/Sylvan.Data.Excel/files/13904836/ChartSheet.xlsx)

I took a shot at fixing the issue in this PR: #150

**Comment by MarkPflug** [comment]
Thanks for providing the fix.
