### ISSUE TITLE
Possibility to write huge Excel / CSV files

### ISSUE THREAD

**Issue by vaceslav** [MarkPflug/Sylvan.Data.Excel#154]
Hi,
Thank you for really good product. 

Is there any way to write asynchronously Excel/CSV files?

My use case is: -> I get a stream of data and I need to write it to the file. Ofc without to use lot of memory. 

Excel files should contains 1_000_000 rows and csv files until 5 millions row.

At the moment it is not possible to write to the same worksheet twice.

**Comment by MarkPflug** [comment]
Sorry, it isn't clear to me what you're trying to do.

It is possible to write large files, but the Excel writer expects to write an entire sheet in one pass, there's no support for editing/appending.

**Comment by vaceslav** [comment]
Thank you for your answer.

I have many microservices.  One microservice (service A) sends data to another one (service B) in an async stream way (grpc async stream).

I want to avoid keeping data in Service B. Because there is a lot of data. Around one million rows and 1500 columns. 
I get from my stream always 1000 rows in a chunk.
It would be great if we could open a worksheet and save data to the file without having to keep it in memory. 

We using your great library for reading Excel files. It works with an extremely low memory footprint.  But for writing that is not the case. 
As a workaround, we using now the library: [LargeXlsx](https://github.com/salvois/LargeXlsx) for writing excel files. With that library, it is possible to write rows from a stream without keeping it in memory. 

It would be great if your library would support both reading and writing in a very performant and memory-saving way.

**Comment by MarkPflug** [comment]
You'll probably have to continue using LargeXlsx then. LargeXlsx, by default, will write xlsx files with inline-string values, allowing the file to be written in a forward-only streaming manner. My library only supports the shared-string table mechanism for xlsx files, which means that all unique strings are held in memory as the file is written. This typically produces much smaller files, but at the expense of having to hold some values in memory.
