### ISSUE TITLE
datatypes of columns or cells 

### ISSUE THREAD

**Issue by ps-nk** [MarkPflug/Sylvan.Data.Excel#156]
Hello Mark,

Thanks again for the great project, I'm super happy so far and I really like the performance :-) 

I currently have a problem with xlsx files that actually only have one line and I can't really derive a data type. Despite all attempts, e.g. with formatting as a number etc. I have also tried using the GetExcelDataType() method, but only ever got a string. 

We have now planned to store the desired data type as a comment in the defined cell.
![image](https://github.com/MarkPflug/Sylvan.Data.Excel/assets/62747555/54904d54-55a3-4917-bb0d-ebb6b7dc2856)

Unfortunately, I have not found a way to read a comment in the cell in the documentation. 
Is this correct or do you have a tip for me on how I can implement this relatively quickly?

Thank you 
nk-cmd

**Comment by MarkPflug** [comment]
No, there is no API for reading comments. It is expected that you would either know the schema ahead of time, or use the GetExcelDataType/GetFieldType. However, as you've found, the field type for Excel files is often times "String", even when the string values might represent something else.
You can try using the Sylvan.Data nuget package as well, which provides the Sylvan.Data.SchemaAnalyzer type. This will look at the data in the file and try to determine the column types by value.  To use this, you need to do two passes over the data, once for the schema analysis, then a second pass to process the data using the provided schema.

You can look at the unit tests to get an idea how it works: https://github.com/MarkPflug/Sylvan/blob/main/source/Sylvan.Data.Tests/SchemaAnalyzerTests.cs
These tests use the Sylvan.Data.Csv.CsvDataReader, but work the same way with the ExcelDataReader.
