### ISSUE TITLE
Empty cells when calling GetRecordsAsync on reader returned by Validate

### ISSUE THREAD

**Issue by sherman89** [MarkPflug/Sylvan.Data.Excel#180]
Calling the async version of `GetRecords` (`GetRecordsAsync`) on a `ValidatingDataReader` returned by Validate method, produces a non-empty array but with empty/default values for all cells.

```csharp
await using var edr = await ExcelDataReader.CreateAsync("TestData/Data_ENG.xlsx");

var reader = edr.Validate(context => true);

var results = reader.GetRecords<UserRecord>().ToList();

// Comment GetRecords above, uncomment below, observe how array with default values is produced
// var results = await reader.GetRecordsAsync<UserRecord>().ToListAsync();

foreach (var userRecord in results)
{
    Console.WriteLine($"Id: {userRecord.Id}");
}
```

I'm using `ToListAsync` from `System.Linq.Async` but doing it "natively" doesn't work either:
```csharp
var results = reader.GetRecordsAsync<UserRecord>();

await foreach (var userRecord in results)
{
    Console.WriteLine($"Id: {userRecord.Id}");
}
```

Result:
![image](https://github.com/MarkPflug/Sylvan.Data.Excel/assets/20951158/8617449f-3f76-45a9-a7ca-76eb01919ffc)

Repo that reproduces the issue:
https://github.com/sherman89/SylvanDataExcelTest.ReadAsync

Thank you!

**Comment by MarkPflug** [comment]
This was actually a bug in the Sylvan.Data library, where the validation reader didn't handle async reads correctly. This is fixed with Sylvan.Data v0.2.15: https://www.nuget.org/packages/Sylvan.Data/0.2.15
