### ISSUE TITLE
BindingMode `DataBindingMode.Any` expects at least 1 column

### ISSUE THREAD

**Issue by sherman89** [MarkPflug/Sylvan.Data.Excel#181]
Reading from an empty worksheet throws an exception even if `BindingMode` is set to `DataBindingMode.Any`, but with at least 1 column it doesn't.

It seems like a bug since the documentation suggests that ANY combination of unbound columns and properties would be allowed?

Project to reproduce bug: https://github.com/sherman89/SylvanDataExcelTest.ReadAsync

**Comment by MarkPflug** [comment]
This is by-design. The intent was the raise an error when your target object has properties a, b, c, while your data source has columns d, e, f and thus nothing binds. In the case that your data source has zero columns, it is trivial to check the FieldCount before binding if you want to avoid this error. The documentation should probably be updated to mention this.
