### ISSUE TITLE
Read URL of an HyperText Cell

### ISSUE THREAD

**Issue by cinziapomoni4** [MarkPflug/Sylvan.Data.Excel#187]
I have been trying to extract the URL address of an hypertext cell on a file I'm reading in, but I could't find out how to get the link and not the hypertext string. 
Which method can I use?

**Comment by MarkPflug** [comment]
Unfortunately, reading the hyperlink URL is not supported. The way excel stores this data doesn't make it possible to read the URL in a forward-only way; the hyperlink data is written at the very end of the sheet file, and the cell itself doesn't even indicate that it *is* a link. I'm sure there are other libraries that provide this functionality though, but I'm not sure which ones.
