### ISSUE TITLE
ExcelDataReader.GetRecords missing?

### ISSUE THREAD

**Issue by jacksorjacksor** [MarkPflug/Sylvan.Data.Excel#191]
Hi there,

In the README's [Bind Excel data to objects using Sylvan.Data](https://github.com/MarkPflug/Sylvan.Data.Excel/tree/main?tab=readme-ov-file#bind-excel-data-to-objects-using-sylvandata) sample, ExcelDataReader.GetRecords<> is used for casting each row of the Excel file into the `MyRecord` type:

```
using var edr = ExcelDataReader.Create("data.xlsx");
foreach (MyRecord item in edr.GetRecords<MyRecord>())
{
    Console.WriteLine($"{item.Name} {item.Quantity}");
}
```

However ExcelDataReader doesn't currently appear to contain a reference to `GetRecords` - what should be used instead?

Thanks!

Rich

**Comment by MarkPflug** [comment]
You need to add the separate Sylvan.Data nuget package. GetRecords is an extension method defined in that package.
