### ISSUE TITLE
first row of data is a merged header

### ISSUE THREAD

**Issue by FreeVB** [MarkPflug/Sylvan.Data.Excel#192]
If the first row of data is a merged header row, how to skip reading from the second row。

**Comment by MarkPflug** [comment]
call Read() to skip the merged header, then call Initialize() to use the second row as the header row.

**Comment by FreeVB** [comment]
using var edr = ExcelDataReader.Create("data.xlsx");
foreach (MyRecord item in edr.GetRecords<MyRecord>())
{
    Console.WriteLine($"{item.Name} {item.Quantity}");
} 
Thank you for your reply.
Why can't I find the GetRecords property in the description file in the code?
