### ISSUE TITLE
converting Xlsx to Xlsb file removes number cells.

### ISSUE THREAD

**Issue by np-Complete-0** [MarkPflug/Sylvan.Data.Excel#194]
Conversion from Xlsx to Binary form of excel file Xlsb generates binary file nicely and it reduces the size. However, it replaces number cells with text cells.

**Comment by MarkPflug** [comment]
You need to provide a schema that defines the data types of your file. The default schema treats every column as strings, which is what causes this behavior. You can change it to `Dynamic` which will cause every cell to be inspected independently.

```
var opts = new ExcelDataReaderOptions { Schema = ExcelSchema.Dynamic};
using var r = ExcelDataReader.Create("data.xlsx", opts);
using var w = ExcelDataWriter.Create("data.xlsb");
do
{
    w.Write(r, r.WorksheetName);
} while (r.NextResult());
```
