### ISSUE TITLE
Conversion to CSV using Sylvan.Data.Csv sometimes writes 0 byte file 

### ISSUE THREAD

**Issue by ChandlerPalmer** [MarkPflug/Sylvan.Data.Excel#195]
I've noticed some cases where trying to convert an excel sheet to csv results in losing all the data on that sheet with no error or warning thrown. I'm using Sylvan.Data.Csv version 1.2.7 and Sylvan.Data.Excel 0.4.25. Updating the csv library to the latest did not change anything here. 

Case 1: Programmatically making an excel file 

Here I wrote a unit test to test this behavior and we can see the underlying stream after writing to the csv is empty. I have never seen a case where this works in my testing. 

![Screenshot 2024-11-21 at 4 51 08 PM](https://github.com/user-attachments/assets/6bfb24b9-4709-44d4-a795-af9d6a4ea99a)
![Screenshot 2024-11-21 at 4 54 02 PM](https://github.com/user-attachments/assets/12ca09b2-1116-4381-a7b7-5688910a0031)
![Screenshot 2024-11-21 at 4 48 52 PM](https://github.com/user-attachments/assets/05172e1e-c4f5-48a0-8384-10609f838e1d)

Case 2: This file that doesn't work 

For some reason this file wont be converted

[TestBugReport.xlsx](https://github.com/user-attachments/files/17873919/TestBugReport.xlsx)

![Screenshot 2024-11-22 at 11 13 03 AM](https://github.com/user-attachments/assets/5345ca54-1071-48f8-a872-47359df128d6)
![Screenshot 2024-11-22 at 11 12 01 AM](https://github.com/user-attachments/assets/8f571092-bc52-4109-9be8-d8336109fe39)

Case 3: This file that does work 

I don't know what the difference is between this file and the last one, but this one does convert and I get a good looking csv and the end of it. 

[BugReport2.xlsx](https://github.com/user-attachments/files/17873923/BugReport2.xlsx)

![Screenshot 2024-11-22 at 11 08 18 AM](https://github.com/user-attachments/assets/701a5911-a8c0-45d9-b864-33ae7558082b)
![Screenshot 2024-11-22 at 11 10 42 AM](https://github.com/user-attachments/assets/3af6cf0a-8b69-4289-9a76-c81f81d5ee0f)

**Comment by MarkPflug** [comment]
Provide code as text, not screenshots. I'm not interested in trying to repro your issue by transcribing your screenshotted code into text. The XXXDataWriter types are all disposable, and it looks like you aren't disposing things. Specifically, with the CsvDataWriter, the last block of data is flushed on dispose, so if you don't dispose you won't get the last buffer-ful of data, which might be the entire file if your input is small.

**Comment by ChandlerPalmer** [comment]
Ah I see, flushing the data writer solved the issue.
