### ISSUE TITLE
XlsWorkbookReader+RecordReader

### ISSUE THREAD

**Issue by FreeVB** [MarkPflug/Sylvan.Data.Excel#202]
XlsWorkbookReader+RecordReader
The ReadStringBuffer method in the XlsWorkbookReader+RecordReader class needs to be appended with System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance); Otherwise, an error will occur when reading Unicode content.

**Comment by MarkPflug** [comment]
The expectation is that the user of the library will call that before using the .xls reader if that's something they need support for. I don't want to call that inside my code, because it isn't needed in all cases. I should call this out in the documentation though. Thanks.
