### ISSUE TITLE
Duplicate key crash, when creating xlsx reader

### ISSUE THREAD

**Issue by 0x410c** [MarkPflug/Sylvan.Data.Excel#23]
stacktrace :
   ```
 System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException<T>(T)
    System.Collections.Generic.Dictionary<TKey, TValue>.TryInsert(TKey, TValue, System.Collections.Generic.InsertionBehavior)
    System.Collections.Generic.Dictionary<TKey, TValue>.Add(TKey, TValue)
    Sylvan.Data.Excel.XlsxWorkbookReader.XlsxWorkbookReader(System.IO.Stream, Sylvan.Data.Excel.ExcelDataReaderOptions)
    Sylvan.Data.Excel.ExcelDataReader.Create(System.IO.Stream, Sylvan.Data.Excel.ExcelWorkbookType, Sylvan.Data.Excel.ExcelDataReaderOptions)
    Sylvan.Data.Excel.ExcelDataReader.Create(string, Sylvan.Data.Excel.ExcelDataReaderOptions)
```

can provide the file, but it has some sensitive information.

**Comment by 0x410c** [comment]
```
this.formats = ExcelFormat.CreateFormatCollection();
foreach (object obj2 in xmlNodeList)
{
	XmlElement xmlElement2 = (XmlElement)obj2;
	int key = int.Parse(xmlElement2.GetAttribute("numFmtId"));
	ExcelFormat value = new ExcelFormat(xmlElement2.GetAttribute("formatCode"));
	this.formats.Add(key, value);
}
```
here the this.formats dictionary already contains key with value 0, it tries to add another value with key 0 and then it crashes.

**Comment by MarkPflug** [comment]
Is this file from Excel? Or from something else, like google sheets?

**Comment by 0x410c** [comment]
its from excel, but not sure, its a third party provided file. i can provide the file privately if you wanna look at

**Comment by 0x410c** [comment]
also the file is parsed perfectly by ExcelDataReader lib.

**Comment by MarkPflug** [comment]
The "0" format is typically the "general" format, the default for excel. I've never seen it explicitly recorded in a file. There are a standard set of formats that are implicitly defined. The fix for this should be easy enough. That line of code should be changed from dictionary.Add(id,format) to dictionary[id] = format. I won't be able to address this for while though, as I'm away from my development machine. If you want to submit a PR, I can merge it when I'm back at the keyboard.

**Comment by 0x410c** [comment]
ok i will try, if this fixes the issue, also i was debugging using dnspy and not directly in source, i will verify more deeply.

**Comment by 0x410c** [comment]
library do not crash with the fix but, i see nothing in data, empty strings are returned

**Comment by MarkPflug** [comment]
if you feel comfortable, you can email me the file at mark.pflug@live.com. I can take a look, but it might be a week or two before I have the time to investigate.

**Comment by 0x410c** [comment]
no problem, take a look when u can, untill then i will try if i can resolve the issue

**Comment by MarkPflug** [comment]
I just pushed version 0.1.8-b0001 (prerelease) to nuget. It should fix the two issues you encountered here. I think that xlsb likely has a similar issue that I need to fix before I push 0.1.8.

**Comment by 0x410c** [comment]
great! i will check

**Comment by 0x410c** [comment]
working, thanks, you can close the issue, one suggestion u can use ExcelDataReader input samples for more reliability, the library is great, but reliability is what i am concerned about. Thanks again.
