### ISSUE TITLE
Headers not in first row, when reading xlsb files

### ISSUE THREAD

**Issue by 0x410c** [MarkPflug/Sylvan.Data.Excel#24]
> By default, it will expect the first row of each sheet to contain headers. This can be disabled however. When disabled, columns can only be accessed by ordinal.

as per your comment, this should be the default behaviour, but in case of xlsb file headers are not in the first row.
to check if headers are being read i tried
`_reader.GetColumnSchema()[0].ColumnName`

which successfully gives the column header name.

**Comment by MarkPflug** [comment]
I think this is a case of my documentation being poorly worded. The default behavior expects the first row of the sheet to contain the headers. This means that immediately after calling `ExcelDataReader.Create`, and before calling `Read`, you should be able to access the header names by calling `GetName(int ordinal)`. However, if you call `Create` and pass in an `ExcelDataReaderOptions` with `Schema` set to `ExcelSchema.NoHeaders`, it will not expect the first row to contain headers. It would then expect the first row to contain data, and the column names would be undefined; `GetName` would return an empty string.

**Comment by 0x410c** [comment]
understood.
