### ISSUE TITLE
Sylvan.Data.Excel.ExcelFormulaException, when reading xlsx values

### ISSUE THREAD

**Issue by 0x410c** [MarkPflug/Sylvan.Data.Excel#25]
stack trace :
```
Sylvan.Data.Excel.XlsxWorkbookReader.GetString(int)
Sylvan.Data.Excel.ExcelDataReader.GetValue(int)
```

i can provide the file, if there is any way i can turn off formula processing than that can be a valid fix too, it will increase performance too i guess?

**Comment by MarkPflug** [comment]
You can disable formula errors by setting the ExcelDataREaderOption.GetErrorAsNull to true. This makes is so that any cell that contains a formula error will be read as if it were empty/null instead.

**Comment by 0x410c** [comment]
still same error, after adding option too

**Comment by MarkPflug** [comment]
You passed the ExcelDataReaderOptions to ExcelDataREader.Create and you're still seeing formula errors? If so, you're going to need to provide more info, what sheet, row, column the error is coming from, because I cannot repo with that file you provided.

**Comment by 0x410c** [comment]
Worksheet name : 2G
row : 20596
column : 11

**Comment by 0x410c** [comment]
Row Number 20596. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 20596. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 20596. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 22130. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 22130. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 22130. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 22327. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 22327. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 22327. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 23175. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 23175. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 23175. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 28775. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 28775. Column : 11
Exception thrown: 'Sylvan.Data.Excel.ExcelFormulaException' in Sylvan.Data.Excel.dll
Row Number 28775. Column : 11
