### ISSUE TITLE
xlsx only first column values are getting returned

### ISSUE THREAD

**Issue by 0x410c** [MarkPflug/Sylvan.Data.Excel#27]
sent the file.

**Comment by MarkPflug** [comment]
This is because "FieldCount" is based off the number of columns in the first row. You can use RowFieldCount when the file contains variable number of columns, to get the number of columns in the current row.

**Comment by 0x410c** [comment]
this in turns generates exception 
System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name'

**Comment by MarkPflug** [comment]
I think this is the same issue that was exibiting in xlsx. Should be fixed in 0.1.8-b0002: https://www.nuget.org/packages/Sylvan.Data.Excel/0.1.8-b0002

**Comment by 0x410c** [comment]
tried but not working same behaviour
