### ISSUE TITLE
Forced Int32

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#32]
Hello Mark, 

I noticed an exception on below : `{"Value must be non-negative and less than or equal to Int32.MaxValue. (Parameter 'count')"}`

This is caused duet o the fact that one value is well above `int32` range, although i though that it would be mapped as `string?`, those values are `decimal` in `.xslb`. spreadsheet. Value : "-11001000000"

I tried both mapping fields as `decimal?`, `decimal`. In my JoinHeaders() method, non of this worked. Once line was manually removed all worked fine. 

```
        private List<T>? SylvanReader<T>()
        {
            try
            {
                var options = new SylExcel.ExcelDataReaderOptions { Schema = SylExcel.ExcelSchema.Default, GetErrorAsNull = true };
                //collect data
                using (SylExcel.ExcelDataReader excelDataReader = SylExcel.ExcelDataReader.Create(Setup.FilePath, options))
                {
                    //loop to locate needed sheet from passed setup
                    while (excelDataReader.WorksheetName != Setup.SheetName)
                    {
                        excelDataReader.NextResult();

                        if (excelDataReader.WorksheetName == null)
                        {
                            //throw exception, that sheet was not located
                            throw new Exception(string.Format("Didn't find the sheet: {0}", Setup.SheetName));
                        }
                    }
                    //loop to find headers, this will allow to skip unwanted rows, such as comments, empty lines etc.
                    for (int i = 0; i < Setup.StartRow; i++)
                    {
                        excelDataReader.Read();
                    }
                    //get all coulmns in file to column specified as max
                    //JoinHeaders is a method that returns array of needed sheets, and not needed as int. 
                    //excample: Data1, Data2, 2, 3, Data3, 5 as string 
                    var schema = Schema.Parse(Setup.JoinHeaders());

                    excelDataReader.InitializeSchema(schema.GetColumnSchema(), useHeaders: true);

                    //JoinHeaders is a method that returns only array of needed sheets. 
                    //excample: Data1, Data2, Data3 as string[]
                    var dataReader = excelDataReader.Select(Setup.NeededHeaders());
                    var binderOptions = new DataBinderOptions
                    {
                        InferColumnTypeFromMember = true,
                        BindingMode = DataBindingMode.Any
                    };
                    DataBinder.Create<T>(dataReader, binderOptions);
                    return dataReader.GetList<T>().ToList();
                }
            }
            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
```

**Comment by KMastalerz** [comment]
![Capture](https://user-images.githubusercontent.com/87186377/154816472-df9feb1a-a078-4501-a68a-6f688a10320d.PNG)

Also, it's at some later stage than mapping itself.

**Comment by KMastalerz** [comment]
Ok, 

Error lies somewhere else, it seems i have to delete any line and it's working. Max = 37405, not sure whats going on.

**Comment by MarkPflug** [comment]
You'll need to provide the schema that is defined here:
`var schema = Schema.Parse(Setup.JoinHeaders());`
And the type `T` that you are trying to bind to.
Honestly, this sounds like correct behavior. If you are trying to bind a numeric value to an integer field that is outside of the range of integers, I wouldn't expect it to work.

**Comment by KMastalerz** [comment]
That's not really the case, it's quite wierd for me.  Like i said, code seems to not work when i replace some data, but it works when i replace a lot of them, when i delete one row or some irrelevant sheets for me. 

**Class:**
```
    public class ExcelInvoice
    {
        public string? HashKey { get; set; }
        public bool? IsActive { get; set; }
        public string? GenKey { get; set; }
        public int? InsertID { get; set; }
        public string? SupplierNumber { get; set; }
        public string? CustomerNumber { get; set; }
        public string? InvoiceNumber { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? OriginalInvoceAmount { get; set; }
        public string? OriginalInvoceCurrency { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string? BaswareStatus { get; set; }
        public string? Reference { get; set; }
        public string? SupplierCountry { get; set; }
        public string? SupplierRegion { get; set; }
        public string? CustomerCountry { get; set; }
        public string? CustomerRegion { get; set; }
        public string? InvoiceType { get; set; }
        public decimal? InvoiceBalance { get; set; }
        public string? InvoiceBalanceCurrency { get; set; }
        public string? WHTSmallDifference { get; set; }
        public decimal? LocalAmount { get; set; }
        public int? DaysOutstanding { get; set; }
        //additional data to be added
        public string ReportType { get; set; }
        public string FileHash { get; set; }
    }
```
**JoinHeaders()**

"SupplierCountry,SupplierRegion,2,SupplierNumber,4,5,CustomerNumber,CustomerCountry,CustomerRegion,9,10,11,InvoiceNumber,InvoiceType,DueDate,OriginalInvoceCurrency,OriginalInvoceAmount,InvoiceBalance,InvoiceBalanceCurrency,19,20"

**NeededHeaders()**

returns an `string[]` array, of: "SupplierCountry, SupplierRegion, SupplierNumber, CustomerNumber, CustomerCountry, CustomerRegion, InvoiceNumber, InvoiceType, DueDate, OriginalInvoceCurrency, OriginalInvoceAmount, InvoiceBalance, InvoiceBalanceCurrency"

I tried to trace where it crashes with below (without modifications to file, but it seems that this is shifting once it crashed at 20,000 the other one it went to 31,000) i was just debugging the app as i modified static class with no file and code modifications. It always crashes on `binder.Bind(reader, item);` though.

```
            var binder = DataBinder.Create<T>(reader);
            int i = 0;
            while (reader.Read())
            {

                var item = (T)Activator.CreateInstance(typeof(T));
                binder.Bind(reader, item);
                if(i== 31685)
                {
                    int j = 0;
                }
                i++;
                yield return item;
            }
```

Can i trust you to not share the file? I'd publish it on private repository and add you if i cannot modify it.

**Comment by MarkPflug** [comment]
You can email it to me at mark dot pflug at live dot com. Try the latest version of the Sylvan.Data library too; there is a new pre-release version that includes the column ordinal in the binder exception.

**Comment by KMastalerz** [comment]
Nope, still not working. I'll send you excample via email. Although it seems like something with extremly rare occurance. Users could troubleshoot that.

**Comment by MarkPflug** [comment]
mark.pflug@live.com

**Comment by MarkPflug** [comment]
Okay, I can repro the exception with the file you sent. Will take a look and figure out what's going on. Definitely a bug, but it isn't obvious right away. Might not be able to investigate it right away, but I will try to look at it in the next few days.

**Comment by MarkPflug** [comment]
Okay, this ended up being a bug with reading records that span an internal buffer boundary. Just pushed 0.1.8 to nuget which contains the fix.
