### ISSUE TITLE
Extract XLSB 

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#38]
_Setup.JoinHeaders() returns:_ "SupplierCountry,SupplierRegion,SupplierNumber,3,4,5,CustomerNumber,CustomerCountry,CustomerRegion,9,10,11,InvoiceNumber,InvoiceType,DueDate,OriginalInvoiceCurrency,OriginalInvoiceAmount,CurrentBalanceInvoiceAmount,18,19,20,21,22,23,24,25,26,27,28,WHTSmallDifference,30,31,32,33,34,35"

_Setup.NeededHeaders() returns:_
![image](https://user-images.githubusercontent.com/87186377/155222571-60fb4651-da8c-47d6-af27-dc1b14c0a574.png)

**File:**
On Email

**Issue:**
**Excample:** for InvoiceNumber "353010003330" : Extracts Number - 10728114.41, where it should be different. (as on file :))
When converted to xlsm/xlsx works fine. 
So i checked against previous versions: it had same issue.

**Code:** 
```
                //sylvan option, get error lines as null (example : 20202/02/02 will be extracted as null date)
                var options = new SylExcel.ExcelDataReaderOptions { Schema = SylExcel.ExcelSchema.Default, GetErrorAsNull = true };
                //collect data
                using (SylExcel.ExcelDataReader excelDataReader = SylExcel.ExcelDataReader.Create(Setup.FilePath, options))
                {
                    //loop to locate needed sheet from passed setup
                    while (excelDataReader.WorksheetName != Setup.SheetName)
                    {
                        excelDataReader.NextResult();

                        if (excelDataReader.WorksheetName == null)
                        {
                            //throw exception, that sheet was not located
                            throw new Exception("didnt find the sheet");
                        }
                    }
                    //loop to find headers, this will allow to skip unwanted rows, such as comments, empty lines
                    for (int i = 0; i < Setup.StartRow; i++)
                    {
                        excelDataReader.Read();
                    }
                    //get all coulmns in file to column specified as max
                    var schema = Schema.Parse(Setup.JoinHeaders());

                    excelDataReader.InitializeSchema(schema.GetColumnSchema(), useHeaders: true);

                    var dataReader = excelDataReader.Select(Setup.NeededHeaders());
                    var binderOptions = new DataBinderOptions
                    {
                        InferColumnTypeFromMember = true,
                        BindingMode = DataBindingMode.Any
                    };
                    DataBinder.Create<T>(dataReader, binderOptions);
                    return dataReader.GetList<T>().ToList();
                }
```

**Class of T:** 
```
    public class ExcelInvoice
    {
        public string? HashKey { get; set; }
        public bool? IsActive { get; set; }
        public string? GenKey { get; set; }
        public int? InsertID { get; set; }
        public string? SupplierNumber { get; set; }
        public string? CustomerNumber { get; set; }
        public string? InvoiceNumber { get; set; }
        public DateTime? DueDate { get; set; }
        public decimal? OriginalInvoceAmount { get; set; }
        public string? OriginalInvoceCurrency { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string? BaswareStatus { get; set; }
        public string? Reference { get; set; }
        public string? SupplierCountry { get; set; }
        public string? SupplierRegion { get; set; }
        public string? CustomerCountry { get; set; }
        public string? CustomerRegion { get; set; }
        public string? InvoiceType { get; set; }
        public decimal? InvoiceBalance { get; set; }
        public string? InvoiceBalanceCurrency { get; set; }
        public string? WHTSmallDifference { get; set; }
        public decimal? LocalAmount { get; set; }
        public int? DaysOutstanding { get; set; }
        //additional data to be added
        public string ReportType { get; set; }
        public string FileHash { get; set; }
    }
```

**Comment by KMastalerz** [comment]
Damn, cannot sent file its too large...

**Comment by MarkPflug** [comment]
Try email?

**Comment by KMastalerz** [comment]
Tried again, not sur if it went ^^ got error at 1st time.

**Comment by MarkPflug** [comment]
Try this: copy the problematic value into new xlsb with just that value in the A1 cell.

**Comment by MarkPflug** [comment]
I got the test.xlsb in email

**Comment by KMastalerz** [comment]
It's over 1,000 rows out of 94,000, but i assume same issue. 
I made it a tad smaller, and removed some sheets as they taken most of the space. Run the code seems to reproduce the error. No error mssg this time :)

This report is manually prepared and some data is taken also from BI

**Comment by KMastalerz** [comment]
I have to sleep now, it's 11PM for me, If anything else will be needed i will reply tomorrow ASAP.

**Comment by MarkPflug** [comment]
I cannot reproduce this. What do you mean *exactly* when you say, "Extracts Number"? You mean the `InvoiceNumber` on the `ExcelInvoice` is `"10728114.41"`? Remind me what your `GetList<T>` method looks like.

**Comment by MarkPflug** [comment]
Here is the code I was testing with:
https://gist.github.com/MarkPflug/3e372f60ffc649fd5b8901f3c92e0014

**Comment by KMastalerz** [comment]
```
        public static IEnumerable<T> GetList<T>(this DbDataReader reader)
        {

            var binder = DataBinder.Create<T>(reader);
            while (reader.Read())
            {
                var item = (T)Activator.CreateInstance(typeof(T));
                binder.Bind(reader, item);
                yield return item;
            }
        }
```
""Extracts Number"? You mean the InvoiceNumber on the ExcelInvoice is "10728114.41"?" - This is regarding amount, it's mapping 10728114.41 where on file it's -9303,83 this excample is based on Invoice Number: 353010003330 from yesterdays Test file. Todays issue #39 is relating to xlsx file where on the other hand Invoice number is incorrect (different file, sent today)

**Comment by KMastalerz** [comment]
after binding all i get the records by: 

var testlist = excelinvoices.Where(invoice=>invoice.InvoiceNumber == "353010003330 ").ToList();
this way im able to view the mapping on specific file.

**Comment by MarkPflug** [comment]
You mean the "OriginalInvoceAmount" property?

**Comment by KMastalerz** [comment]
Exactly, i created this quick test it's based on mymethodology. 
[SylvanTest.zip](https://github.com/MarkPflug/Sylvan.Data.Excel/files/8126457/SylvanTest.zip)

**Comment by MarkPflug** [comment]
You need to provide better descriptions. You didn't say "OriginalInvoceAmount" anywhere in your description. Also, there is a typo in OriginalInvoceAmount.

**Comment by KMastalerz** [comment]
Yup there was a typo i noticed that before but i must have repasted it incorrectly (maybe from some file i had, forgot right now). 
Nevertheless, issue still occurs, same as issue in #39. I'll be more specific and exact in the future.

**Comment by KMastalerz** [comment]
Yes, values seems to be correct, tomorrow ill be able to do more extensive test for those values :)
