### ISSUE TITLE
Exctract XLSX

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#39]
I Have another missmatch, and also on only some of the rows. Excample InvoiceNumber missmatch on row = 95 instead of "125060" it appears as "0". Tried to convert to xlsm & xlsb (same errors).

**FILE:**  Email

_Setup.JoinHeaders() returns:_
"0,CustomerNumber,2,3,SupplierNumber,SupplierCountry,6,InvoiceNumber,8,9,DueDate,11,12,InvoiceType,14,15,16,17,OutstandingDays,19,OriginalInvoiceAmount,21,CurrentBalanceInvoiceAmount,23,OriginalInvoiceCurrency"

_Setup.NeededHeaders() returns:_
![image](https://user-images.githubusercontent.com/87186377/155323108-82045267-814b-4819-bfae-57130bf7f7db.png)

Code and class like in previous issues.

**Comment by MarkPflug** [comment]
I cannot reproduce this one.
You are saying that the Invoice Number in cell H95 is read as "0" instead of "125060"?

**Comment by KMastalerz** [comment]
You might be right here, im testing this right now, and it actually appears that it's changing after my formatting, not extract. That's my bad sorry for that, should have checked that. This one can be closed.
