### ISSUE TITLE
ExcelDataReader Create suggestions

### ISSUE THREAD

**Issue by CaiusJard** [MarkPflug/Sylvan.Data.Excel#44]
For the `Create(string path)` overload, allow the passing of a ExcelWorkbookType so we can pass paths of any extension (like .tmp from path.gettempfilename) together with an overriding type

Add a message to the ArgumentException throw to indicate something like *"The file extension {Path.GetExtension(filename)} is not supported. Pass a path with any supported extension: [{string.Join(", ", FileTypeMap.Keys}] or use the `fileType` argument to override extension-based file-type detection"*

(Motivation for raising this issue was, I put a .tmp filename in and just got a bland *"System.ArgumentException: 'Arg_ArgumentException Arg_ParamName_Name'"* error out of it - had to read the code to determine that extension was used to determine type)

**Comment by CaiusJard** [comment]
Also, when using this overload the file is still locked even after the EDR is disposed. I've switched to using the stream overload so I can dispose the stream myself, but perhaps using Create(string) should retain/dispose the FileStream it creates

**Comment by MarkPflug** [comment]
I want to give a bit of thought to this. It might be better to *detect* the file type if the extension is unknown. It should be relatively straightforward to identify the file type by looking at the header.

The second issue, with file being locked is definitely a bug. I've fixed that with #45. Will be published to nuget as 0.1.11-b0003 shortly.

**Comment by MarkPflug** [comment]
I think the existing API of accepting a Stream and the workbook type is sufficient here. The dispose issue has been fixed, so thanks for pointing that one out.

**Comment by CaiusJard** [comment]
So how about an exception message of *The file extension {Path.GetExtension(filename)} is not supported. Pass a path with any supported extension: [{string.Join(", ", FileTypeMap.Keys}] or use the Create(Stream, ExcelWorkbookType) overload to override extension-based file-type detection* then? 

At the moment the exception message if the file extension isn't supported, is unhelpful: "Value does not fall within the expected range: filename"
