### ISSUE TITLE
Improve strongly-typed accessors

### ISSUE THREAD

**Issue by cirrusone** [MarkPflug/Sylvan.Data.Excel#47]
I have scenarios where imported Excel columns have empty or unknown values as strings rather than required data type, eg <empty>, "'-" etc. (Unfortunately we can't always control what people input in Excel).

When using the strongly-typed accessors such as `DateTime dt = edr.GetDateTime(i);` this will throw error `Input string was not in a correct format.`. I thought GetErrorAsNull might fix this but this seems to only handle actual cell errors rather than casting errors.

Is it possible to either add nullable types or ability to handle fail casts without throwing errors?

Something like this...

`DateTime? dt = edr.GetDateTime(i, returnNullOnFail: true);`

or 

`DateTime? dt = edr.GetDateTimeNullable(i);`

At the moment I have to return all data as string and handle parsing manually.

**Comment by MarkPflug** [comment]
The strongly-typed accessors cannot be changed; their behavior is dictated by the I/DbDataReader types that they must conform to. I would recommend that you create extension methods on `DbDataReader` to add the behavior that you want.

Something like:

```C#
static DataExtensions {

public static bool? GetBooleanOrNull(this DbDataReader reader, int ordinal) {
  try {
    return reader.GetBoolean(ordinal);
  } catch{
    return null;
  }
}
}
```

There might be some complexity if you want the behavior of `IsDbNull` to match however. That's probably not important for your use case though, if you aren't going to be using the `DbDataReader` defined methods directly.
