### ISSUE TITLE
System.Memory and netstandard2.0

### ISSUE THREAD

**Issue by charles-durrant-tr** [MarkPflug/Sylvan.Data.Excel#49]
Hi Mark, 

I've just put in a pull request and thought I'd give you some background. 

I work with huge Excel files, 1 million lines with >300 columns is not uncommon and as you already know processing them in other libraries is very slow and memory hungry. Luckily I came across your library as I was about to embark on using the MS libraries to SAX parse xlsx files. 

I integrated your library into our code. We have a configurable importer than can use different excel extractors as we've used a number of the years and each has their own set of issues. We have a mixed set of .net4.8 code and .netstandard and on adding your library I got a runtime error with respect to System.Memory, rightly as to use  Span you have forced a dependency on a later version. 

Unfortunately with the tangled web of references we have that fixed dependency was not possible to handle. I thus changed the code to no longer have the dependency. It's not a complex change and maintains the benefits of Span in netstandard 2.1

Once I had it working I then ran our unit tests against the code and found some issues. Many passed which was great but some failed when compared to the other excel extractors we have. This was great and I'd like to put in further pull requests to fix the issues or post the files with an explanation of the issue, however for me to be of use, I need to the code to not be dependent on the netstandard2.0 System.Memory version specified. Selfish I know...

I also wondered about writing some code to compare the output of say EPPlus which for us is the most reliable library against this library's output. This could be added to each unit test. 

Charlie

**Comment by MarkPflug** [comment]
Thanks Charlie, I'll try to take a look at it soon. It looks pretty straightforward, but I want to run it through the benchmarks I have to make sure that the .NET core code path doesn't regress on perf.

> I need to the code to not be dependent on the netstandard2.0 System.Memory version specified

Can you tell me more? I'm referencing System.Memory v4.5.1. The lowest version I see on nuget is v4.5.0. I don't think I have any reason to prefer 4.5.1 over 4.5.0, so if that would fix it for you that might be the easiest.

**Comment by charles-durrant-tr** [comment]
p.s. I was very happy when I say this project, our Excel importing perf is terrible.

**Comment by MarkPflug** [comment]
I just published your changes with 0.1.11-b0004 to nuget. I need to find time to investigate a potential issue with .xls files before I'm publish a non-pre-release build.

**Comment by charliedurrant** [comment]
No problem and thank you, I'll now start to build up some xlsx case(s) that fail.
