### ISSUE TITLE
Endcoding.Default and xlsx

### ISSUE THREAD

**Issue by charles-durrant-tr** [MarkPflug/Sylvan.Data.Excel#53]
Mark, 

I created another pull request. I fixed an issue with xlsx xml reader and using Ecoding.Default, however the underlying issue of non ascii data is still present in xls/xlb, I didn't want to mess with that as my understanding is poor. 

Unit test added

C

**Comment by MarkPflug** [comment]
Thanks for the PR. I've merged it with fixes for the other formats, and also fixed the blank second sheet tests. Pushed as 0.1.11-b0005 to nuget.

**Comment by charliedurrant** [comment]
Thanks Mark, I'll do some more tests.
