### ISSUE TITLE
Read Exception

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#66]
Exception:  _The ReadValueAsChunk method is not supported on node type EndElement_

                var options = new SylExcel.ExcelDataReaderOptions { Schema = SylExcel.ExcelSchema.Default, GetErrorAsNull = true };
                //collect data
                **using (SylExcel.ExcelDataReader excelDataReader = SylExcel.ExcelDataReader.Create(Setup.FilePath, options))**

Exception occurs on create

File sent via email.

**Comment by MarkPflug** [comment]
Fixed in https://www.nuget.org/packages/Sylvan.Data.Excel/0.2.0-b0002

**Comment by KMastalerz** [comment]
Hello Mark, 
I had send you additional query regarding missing method `InitializeSchema`, how was it replaced?

**Comment by MarkPflug** [comment]
I replaced that method with `Initialize`, which uses the schema that is passed to the constructor options object. The design of the InitializeSchema method felt a bit clumsy and duplicated what was already available via the constructor options.

**Comment by KMastalerz** [comment]
Im getting exception after that change: 
At step: `var dataReader = excelDataReader.Select(Setup.NeededHeaders());`
'Specified argument was out of the range of valid values. (Parameter 'names')'

```
                //collect data
                using (SylExcel.ExcelDataReader excelDataReader = SylExcel.ExcelDataReader.Create(Setup.FilePath, options))
                {
                    //loop to locate needed sheet from passed setup
                    if (!string.IsNullOrWhiteSpace(Setup.SheetName))
                    {
                        while (excelDataReader.WorksheetName != Setup.SheetName)
                        {
                            excelDataReader.NextResult();

                            if (excelDataReader.WorksheetName == null)
                            {
                                //throw exception, that sheet was not located
                                throw new Exception("didnt find the sheet");
                            }
                        }
                    }

                    //loop to find headers, this will allow to skip unwanted rows, such as comments, empty lines
                    for (int i = 0; i < Setup.StartRow; i++)
                    {
                        excelDataReader.Read();
                    }
                    //get all coulmns in file to column specified as max
                    var schema = Schema.Parse(Setup.JoinHeaders());

                    excelDataReader.Initialize();
                    //excelDataReader.InitializeSchema(schema.GetColumnSchema(), useHeaders: true);

                    var dataReader = excelDataReader.Select(Setup.NeededHeaders());
```

**Comment by KMastalerz** [comment]
` var options = new SylExcel.ExcelDataReaderOptions { Schema = SylExcel.ExcelSchema.Default, GetErrorAsNull = true };
I declared headers later on

**Comment by KMastalerz** [comment]
So i wouldn't be able to change schema later on? I can only pass schema during initialization?

**Comment by MarkPflug** [comment]
Technically you can change the schema whenever you want, but it will require more work. The Schema option is of type `IExcelSchemaProvider`. `ExcelSchema` is a simple implementation of that interface. You can provide a custom implementation that allows you to do whatever you want.

**Comment by MarkPflug** [comment]
I'll probably be adding a similar (initialize) API to the csv reader too at some point.
