### ISSUE TITLE
IndexOutOfBounds in XlsxWorkbookReader

### ISSUE THREAD

**Issue by CaiusJard** [MarkPflug/Sylvan.Data.Excel#73]
I've a file here (that I cannot supply publicly, but can work out a way to provide if needed) that causes EDR to throw an IOOB from the constructor for the EDR:

![image](https://user-images.githubusercontent.com/68939130/178659786-56c6bcb6-5f8c-494b-a534-5f19ec5148d3.png)

The xfselem doesn't have a count attribute, so this ends up with `c` as 0, and the `xfMap` is 0 long. I'm wondering if an alternative value for `c` could sensibly be `xfsElem.ChildNodes.Count` ?

The file itself has some issues, but I'm raising a spearate ticket for a feature request for those

**Comment by MarkPflug** [comment]
Got the file. I agree with your analysis. I think that completely ignoring the `count` attribute and just using the child node count is the correct fix. Are you interested in submitting a PR? Or should I just fix it myself?

There is a subsequent issue with the file. The sheet data has inlineStr cells that don't contain any content which I've never seen before. Must be a quirk of the JasperReports tool that created this, and also easy enough to fix it.

**Comment by CaiusJard** [comment]
I realize now I did also note that second problem too; i just commented out the throw and went about my work, forgetting to report it. The workaround I've been using to date was to delete the two blank lines at the head of the file, then re-save in Excel, which probably fixed things up somehow so I experienced neither problem..

Can sub a PR for the first one; are you taking the second or do you want me to roll something in (and what is sensible? string.Empty?) ?

**Comment by MarkPflug** [comment]
Yep, I set the value to string.empty, and set the cell type to null. If you want to roll it all into once PR that works.
