### ISSUE TITLE
Is there a way to skip rows of an excel in order to reach a header row? Feature request a way?

### ISSUE THREAD

**Issue by CaiusJard** [MarkPflug/Sylvan.Data.Excel#74]
I've some files that look like this:

![image](https://user-images.githubusercontent.com/68939130/178657350-19cdcbcd-50cd-4001-8867-dd19bb5f75f1.png)

The two blank rows above the dark grey one are irrelevant to me but EDR experiences an index out of bounds exception if they are present (raised in separate ticket) - I presume because it's running into problems building the column schema. The dark grey row is the header row. The light grey row is a summary row that I can handle normally by skipping the read, but is there a way to skip the first two rows so that EDR parses the headers out of the third row? 

This "has two useless rows" only happens on the first sheet of a multi sheet file, so perhaps a methodology of a callback `Func<object[], bool> IsTheHeaderRow` that I can attach a func to and EDR will call it repeatedly while it hasn't before returned `true` for this sheet; I'll inspect the `object[]` data to see if it's e.g. `"the header I expect in column 1".Equals(myObject[0])`. Some way like this would cope with variable numbers of junk rows before the header, but I could also track a bool in my own code and set a "HeaderRowIndex" option integer differently for the first sheet compared to the others

**Comment by CaiusJard** [comment]
Will do, thanks Mark

**Comment by MarkPflug** [comment]
@CaiusJard I'm assuming this worked. If not, feel free to open a new issue.

**Comment by CaiusJard** [comment]
I'm sure it will; I haven't checked it yet - some other aspect of the project was prioritized (the money part! hah) but I'll be on with it soon
