### ISSUE TITLE
Unfortunately still experiencing issues after secondary initialization. 

### ISSUE THREAD

**Issue by KMastalerz** [MarkPflug/Sylvan.Data.Excel#83]
Here is adjusted application you had sent to replicate the issue with some comments.

Initialy i though that it works, but i selected modified file (that worked with previous solution), not original one. 

[readermod.zip](https://github.com/MarkPflug/Sylvan.Data.Excel/files/9309932/readermod.zip)

**Comment by MarkPflug** [comment]
This is fixed with 0.3.0 (just pushed to nuget). There was a bug when calling `Initialize` on the first row in the file.
