### ISSUE TITLE
=Today() formula returns last saved date rather than current date

### ISSUE THREAD

**Issue by MarcinWatroba** [MarkPflug/Sylvan.Data.Excel#86]
Note I'm using DD/MM/YYYY format in my example.

I had a cell with following formula:
=Today() - AB2 - 10 (15/08/2022 - 02/06/2022 - 10)
In Excel it was displaying the correct value of 65 (days difference). However, both Sylvan and OpenXML were returning 46. It turns out that 46 days was the difference from the last saved date (28/07/2022). Saving the file again fixed the problem and correct value was returned by both Sylvan and OpenXML.

**Comment by MarkPflug** [comment]
This library doesn't provide an execution engine, it simply reads the data that is persisted in the file. There are other libraries that support formula execution, you might try one of those instead. Or, you can implement the formula logic in your C# application, which looks like it is simple date math on another column..
